#!/usr/bin/env bash
test -z $(type -p) || { echo bash required; exit 1; }
set -e
set -u
source ${RRCONFINC}

test -x /usr/bin/apt &&
  exec $replay apt $*

test -x /usr/bin/yum &&
  exec $replay yum $*

log apt and yum support only. patch the package, please...
exit 1
